export const Champions = [
    {name: "Kha'Zix", items: ['RBRB', 'BFBF', 'TearTear', 'NLRTear'],count:0},
    {name: "Pyke", items: ['BFTear', 'CVTear', 'GBNLR', 'SpatTear'],count:0},
    {name: "Zed", items: ['RBRB', 'BFBF', 'BFNC', 'BFGB'],count:0},
    {name: "Katarina", items: ['GBNLR', 'BFNLR', 'NLRNLR', 'NLRSpat'],count:0},
    {name: "Evelynn", items: ['TearTear', 'GBNLR', 'NLRNLR', 'NLRSpat'],count:0},
    {name: "Rengar", items: ['RBRB', 'BFCV', 'BFNC', 'NCNC'],count:0},
    {name: "Akali", items: ['TearTear', 'NCNC', 'BFNLR', 'CVRB', 'GBGB', 'BFCV'],count:0},
    {name: "Camille", items: [],count:0},
    {name: "Fiora", items: ['RBTear', 'BFNLR', 'BFNC', 'RBRB'],count:0},
    {name: "Shen", items: ['NCNC', 'CVCV', 'BFCV', 'GBGB'],count:0},
    {name: "Aatrox", items: ['BFNLR', 'BFCV', 'NCNC', 'CVRB', 'NLRSpat'],count:0},
    {name: "Gangplank", items: ['NCTear', 'GBCV', 'GBNLR', 'BFTear', 'BFCV', 'CVNC'],count:0},
    {name: "Draven", items: ['RBRB', 'BFNC', 'NLRRB', 'NCNC', 'BFBF', 'CVRB', 'BFCV'],count:0},
    {name: "Yasuo", items: ['TearTear', 'CVGB', 'GBGB', 'NCTear', 'CVNC', 'NCNC'],count:0},
    {name: "Lissandra", items: [],count:0},
    {name: "Kennen", items: ['GBNLR', 'BFCV', 'NLRNLR', 'NCNC', 'CVRB'],count:0},
    {name: "Brand", items: ['BFTear', 'RBRB', 'GBNLR'],count:0},
    {name: "Anivia", items: ['GBNLR', 'NLRNLR', 'TearTear'],count:0},
    {name: "Warwick", items: [],count:0},
    {name: "Vi", items: ['CVTear', 'GBGB', 'NLRSpat', 'GBNLR', 'BFTear'],count:0},
    {name: "Rek'Sai", items: ['BFTear', 'NLRRB', 'RBRB', 'CVRB', 'GBGB', 'BFCV'],count:0},
    {name: "Blitzcrank", items: ['NLRNLR', 'BFTear'],count:0},
    {name: "Volibear", items: ['RBRB', 'SpatTear', 'BFBF', 'GBRB', 'NCSpat', 'GBCV', 'BFNC'],count:0},
    {name: "Cho'Gath", items: ['TearTear', 'BFCV', 'GBNLR', 'NLRNLR', 'RBRB', 'NLRSpat'],count:0},
    {name: "Vayne", items: ['RBTear', 'GBRB', 'RBRB', 'NLRRB'],count:0},
    {name: "Varus", items: ['BFTear', 'GBNLR', 'NLRRB', 'RBTear', 'NLRNLR', 'NLRSpat'],count:0},
    {name: "Ashe", items: ['RBTear', 'RBRB', 'NLRRB', 'BFTear'],count:0},
    {name: "Kindred", items: ['NLRSpat', 'BFCV', 'CVRB', 'RBTear'],count:0},
    {name: "Graves", items: ['CVGB', 'GBRB', 'BFBF'],count:0},
    {name: "Jinx", items: ['NCSpat', 'RBSpat', 'RBRB', 'BFNC', 'NLRRB', 'CVGB'],count:0},
    {name: "Tristana", items: ['NCRB', 'NCTear', 'RBSpat', 'BFBF', 'GBRB'],count:0},
    {name: "Lucian", items: ['NCRB', 'NCTear', 'CVGB', 'NLRTear', 'CVNC', 'TearTear'],count:0},
    {name: "Miss Fortune", items: ['TearTear', 'GBNLR', 'BFCV'],count:0},
    {name: "Darius", items: ['GBGB', 'NCNC'],count:0},
    {name: "Garen", items: ['NCNC', 'GBGB', 'CVRB', 'GBNLR'],count:0},
    {name: "Mordekaiser", items: [],count:0},
    {name: "Poppy", items: ['NLRSpat', 'NCNC', 'CVRB', 'GBGB', 'NCNLR'],count:0},
    {name: "Sejuani", items: ['GBNLR', 'BFCV', 'NCNC', 'CVRB', 'GBGB'],count:0},
    {name: "Kayle", items: ['RBSpat', 'NLRSpat', 'BFTear', 'RBTear', 'NCSpat', 'NLRRB', 'RBRB'],count:0},
    {name: "Braum", items: ['CVCV', 'NCNC', 'GBGB'],count:0},
    {name: "Leona", items: ['NLRTear', 'TearTear'],count:0},
    {name: "Kassadin", items: ['RBRB', 'NLRRB', 'NCNC', 'CVRB', 'BFNC', 'NLRNLR'],count:0},
    {name: "Ahri", items: ['RBTear', 'NLRTear', 'TearTear', 'GBNLR', 'NLRNLR'],count:0},
    {name: "Twisted Fate", items: ['RBTear', 'TearTear', 'NLRTear', 'RBRB'],count:0},
    {name: "Lulu", items: ['BFTear', 'NLRRB', 'NLRNLR', 'NCNLR'],count:0},
    {name: "Veigar", items: ['TearTear', 'BFNLR', 'NCNC', 'CVRB', 'RBRB'],count:0},
    {name: "Morgana", items: ['NLRNLR', 'GBNLR', 'CVTear', 'TearTear', 'NCNC', 'BFCV'],count:0},
    {name: "Aurelion Sol", items: ['RBRB', 'BFTear', 'NLRNLR', 'GBNLR'],count:0},
    {name: "Karthus", items: ['GBNLR', 'NLRNLR', 'BFTear', 'TearTear'],count:0},
    {name: "Nidalee", items: ['RBRB', 'RBTear', 'BFNC'],count:0},
    {name: "Elise", items: ['GBGB', 'CVTear'],count:0},
    {name: "Jayce", items: [],count:0},
    {name: "Shyvana", items: ['GBGB', 'CVCV', 'CVRB', 'RBRB', 'BFNC', 'NLRRB'],count:0},
    {name: "Gnar", items: ['GBGB', 'GBRB', 'CVRB', 'NCNC'],count:0},
    {name: "Swain", items: ['GBGB', 'NLRNLR', 'BFNLR', 'GBNLR', 'BFCV', 'TearTear', 'NCNC', 'CVRB'],count:0}
]

export default Champions

// note that the champion array uses values "name" and "items" (for item ids that are good on that champion), rather than the id+name syntax the item arrays have

// also note that this list is INCOMPLETE and completely un-updated.  
// When I find an up-to-date guide on pro-player choices for items in the current patch I will go through and update this list
// For now I added the un-updated list so you have SOMETHING to work with to code around if you get to a point where you want to start implementing champion recommendation
