const FullItems = [
    {id: "BFBF", name: "Deathblade"},
    {id: "BFCV", name: "Guardian Angel"},
    {id: "BFGB", name: "Zeke's Herald"},
    {id: "BFNC", name: "Bloodthirster"},
    {id: "BFNLR", name: "Hextech Gunblade"},
    {id: "BFRB", name: "Giant Slayer"},
    {id: "BFSG", name: "Infinity Edge"},
    {id: "BFSpat", name: "Youmou's Ghostblade"},
    {id: "BFTear", name: "Spear of Shojin"},
    {id: "CVCV", name: "Thornmail"},
    {id: "CVGB", name: "Red Buff"},
    {id: "CVNC", name: "Sword Breaker"},
    {id: "CVNLR", name: "Locket of the Iron Solari"},
    {id: "CVRB", name: "Phantom Dancer"},
    {id: "CVSG", name: "Iceborn Gauntlet"},
    {id: "CVSpat", name: "Knight's Vow"},
    {id: "CVTear", name: "Frozen Heart"},
    {id: "GBGB", name: "Warmog's Armor"},
    {id: "GBNC", name: "Zephyr"},
    {id: "GBNLR", name: "Morellonomicon"},
    {id: "GBRB", name: "Titanic Hydra"},
    {id: "GBSG", name: "Trap Claw"},
    {id: "GBSpat", name: "Frozen Mallet"},
    {id: "GBTear", name: "Redemption"},
    {id: "NCNC", name: "Dragon's Claw"},
    {id: "NCNLR", name: "Ionic Spark"},
    {id: "NCRB", name: "Cursed Blade"},
    {id: "NCSG", name: "Quicksilver"},
    {id: "NCSpat", name: "Runaan's Hurricane"},
    {id: "NCTear", name: "Hush"},
    {id: "NLRNLR", name: "Rabadon's Deathcap"},
    {id: "NLRRB", name: "Guinsoo's Rageblade"},
    {id: "NLRSG", name: "Jeweled Gauntlet"},
    {id: "NLRSpat", name: "Yuumi"},
    {id: "NLRTear", name: "Luden's Echo"},
    {id: "RBRB", name: "Rapidfire Cannon"},
    {id: "RBSpat", name: "Blade of the Ruined King"},
    {id: "RBTear", name: "Statikk Shiv"},
    {id: "RBSG", name: "Repeating Crossbow"},
    {id: "SGSG", name: "Thief's Gloves"},
    {id: "SGSpat", name: "Mittens"},
    {id: "SGTear", name: "Hand of Justice"},
    {id: "SpatSpat", name: "Force of Nature"},
    {id: "SpatTear", name: "Darkin"},
    {id: "TearTear", name: "Seraph's Embrace"}
]

export default FullItems

    
