const FullItems = [
    "BFBF": {id: "BFBF", name: "Deathblade"},
    "BFCV": {id: "BFCV", name: "Guardian Angel"},
    "BFGB": {id: "BFGB", name: "Zeke's Herald"},
    "BFNC": {id: "BFNC", name: "Bloodthirster"},
    "BFNLR": {id: "BFNLR", name: "Hextech Gunblade"},
    "BFRB": {id: "BFRB", name: "Giant Slayer"},
    "BFSG": {id: "BFSG", name: "Infinity Edge"},
    "BFSpat": {id: "BFSpat", name: "Youmou's Ghostblade"},
    "BFTear": {id: "BFTear", name: "Spear of Shojin"},
    "CVCV": {id: "CVCV", name: "Thornmail"},
    "CVGB": {id: "CVGB", name: "Red Buff"},
    "CVNC": {id: "CVNC", name: "Sword Breaker"},
    "CVNLR": {id: "CVNLR", name: "Locket of the Iron Solari"},
    "CVRB": {id: "CVRB", name: "Phantom Dancer"},
    "CVSG": {id: "CVSG", name: "Iceborn Gauntlet"},
    "CVSpat": {id: "CVSpat", name: "Knight's Vow"},
    "CVTear": {id: "CVTear", name: "Frozen Heart"},
    "GBGB": {id: "GBGB", name: "Warmog's Armor"},
    "GBNC": {id: "GBNC", name: "Zephyr"},
    "GBNLR": {id: "GBNLR", name: "Morellonomicon"},
    "GBRB": {id: "GBRB", name: "Titanic Hydra"},
    "GBSG": {id: "GBSG", name: "Trap Claw"},
    "GBSpat": {id: "GBSpat", name: "Frozen Mallet"},
    "GBTear": {id: "GBTear", name: "Redemption"},
    "NCNC": {id: "NCNC", name: "Dragon's Claw"},
    "NCNLR": {id: "NCNLR", name: "Ionic Spark"},
    "NCRB": {id: "NCRB", name: "Cursed Blade"},
    "NCSG": {id: "NCSG", name: "Quicksilver"},
    "NCSpat": {id: "NCSpat", name: "Runaan's Hurricane"},
    "NCTear": {id: "NCTear", name: "Hush"},
    "NLRNLR": {id: "NLRNLR", name: "Rabadon's Deathcap"},
    "NLRRB": {id: "NLRRB", name: "Guinsoo's Rageblade"},
    "NLRSG": {id: "NLRSG", name: "Jeweled Gauntlet"},
    "NLRSpat": {id: "NLRSpat", name: "Yuumi"},
    "NLRTear": {id: "NLRTear", name: "Luden's Echo"},
    "RBRB": {id: "RBRB", name: "Rapidfire Cannon"},
    "RBSpat": {id: "RBSpat", name: "Blade of the Ruined King"},
    "RBTear": {id: "RBTear", name: "Statikk Shiv"},
    "RBSG": {id: "RBSG", name: "Repeating Crossbow"},
    "SGSG": {id: "SGSG", name: "Thief's Gloves"},
    "SGSpat": {id: "SGSpat", name: "Mittens"},
    "SGTear": {id: "SGTear", name: "Hand of Justice"},
    "SpatSpat": {id: "SpatSpat", name: "Force of Nature"},
    "SpatTear": {id: "SpatTear", name: "Darkin"},
    "TearTear": {id: "TearTear", name: "Seraph's Embrace"}
]

export default FullItems

    
